import 'strings.dart';

const en_US = {
  StringStyles.appName: 'BlogTime',
  StringStyles.loading: 'Loading...',
  StringStyles.loginAccountNameHint: 'Please enter the account name',
  StringStyles.loginAccountPwdHint: 'Please enter the password',
  StringStyles.loginAccountRePwdHint: 'Please enter the password again',
  StringStyles.loginButton: 'Login',
  StringStyles.loginSuccess: 'login successful',
  StringStyles.registerButton: 'Register',
  StringStyles.registerServiceTerms:
      'I have read and agreed to the terms of service',
  StringStyles.registerAccountEmpty: 'Please enter user name～',
  StringStyles.registerAccountLength: 'At least 6 usernames～',
  StringStyles.registerPasswordEmpty: 'Please enter the password～',
  StringStyles.registerPasswordLength: 'Password at least 6 digits～',
  StringStyles.registerRePasswordEmpty: 'Please confirm the password～',
  StringStyles.registerRePasswordLength: 'Password at least 6 digits～',
  StringStyles.registerPasswordDiff:
      'The two passwords entered are inconsistent～',
  StringStyles.registerNotServiceTerms: 'Please agree to the terms of service～',
  StringStyles.registerSuccess: 'Registration success～',
  StringStyles.homeComplex: 'comprehensive',
  StringStyles.homeProject: 'project',
  StringStyles.homeMy: 'mine',
  StringStyles.homeCollect: 'collect',
  StringStyles.homePoints: 'Points',
  StringStyles.homePartake: 'Share',
  StringStyles.homeHistory: 'History',
  StringStyles.homeUserInfo: 'Personal information',
  StringStyles.homeAbout: 'About',
  StringStyles.homeShare: 'Share',
  StringStyles.homeFeedback: 'Feedback',
  StringStyles.webEditHint: 'Say something...',
  StringStyles.webNotComment: 'Do not support commenting ye',
  StringStyles.userNickname: 'Nickname',
  StringStyles.userPointsRanking: 'Come and check the ranking list~',
  StringStyles.userRankingTitle: 'Points ranking',
  StringStyles.userRankingNumber: 'Rank',
  StringStyles.userRankingCoin: 'Accumulated points',
  StringStyles.aboutTitle: 'About Bosera',
  StringStyles.aboutVersion: 'Version:',
  StringStyles.aboutBuild: 'build:',
  StringStyles.aboutGithub: 'Github',
  StringStyles.aboutJueJin: 'juejin',
  StringStyles.aboutSupport: 'Technical Support',
  StringStyles.aboutCopyright: 'Copyright@2021\nAll Right Reserved',
  StringStyles.feedbackTitleStar: "Feedback*",
  StringStyles.feedbackHint: "You can enter feedback content here",
  StringStyles.feedbackUploadPhoto: "Upload screenshot",
  StringStyles.feedbackContact: "Contact information",
  StringStyles.feedbackOptional: "(Optional)",
  StringStyles.feedbackConnectQQ: "Contact QQ group:704273239",
  StringStyles.feedbackConnectHint: "Please enter your contact information",
  StringStyles.feedbackSubmit: "Submit",
  StringStyles.feedbackToast: "Choose up to 4~",
  StringStyles.feedbackSuccess: "Feedback success!",
  StringStyles.feedbackContent: "Please fill in the feedback content!",
  StringStyles.pointsDetailTitle: "Points details",
  StringStyles.settingTitle: "Setting",
  StringStyles.settingLanguage: "Language",
  StringStyles.settingLanguageDefault: "Follow System",
  StringStyles.settingCache: "Clear cache",
  StringStyles.settingCacheSuccess: "Clear cache successfully!",
  StringStyles.settingCacheFail: "Failed to clear cache!",
  StringStyles.settingExitLogin: "Sign out",
  StringStyles.pointsNotifySuccess: "Refresh successfully",
  StringStyles.refreshNoData: "No more data",
  StringStyles.refreshError: "Failed to load!",
  StringStyles.refreshPull: "Drop-down loading",
  StringStyles.refreshHeaderIdle: "Pull up to refresh",
  StringStyles.refreshHeaderFreed: "Release refresh",
  StringStyles.refreshHeaderFailed: "Refresh failed!",
  StringStyles.refreshHeaderSuccess: "Refresh successfully",
  StringStyles.collectTitle: "My collection",
  StringStyles.enter: "Confirm",
  StringStyles.quit: "Quit",
  StringStyles.shareApplication: "Practical blog app recommended to you",
  StringStyles.shareHint: "Bosera, your blog steward",
  StringStyles.shareSaveLocal: "Save to local",
  StringStyles.shareBrowser: "Browser opens",
  StringStyles.saveSuccess: "Saved successfully",
  StringStyles.saveFail: "Saved fail",
  StringStyles.tabHome: "FrontPage",
  StringStyles.tabSquare: "Square",
  StringStyles.tabAsk: "Q&A",
  StringStyles.searchHint: "Search what you want",
  StringStyles.search: "Search",
  StringStyles.searchHistory: "Search history",
  StringStyles.searchHotWord: "Hot search list",
  StringStyles.refreshEmpty: 'No more content~',
  StringStyles.tabWechatPublic:
      'Recommend a wave of excellent technical public accounts~',
  StringStyles.tabWechatSwitch: 'Change batch  ',
  StringStyles.tabWechatDelete: 'not interested',
  StringStyles.historyTitle: 'Browsing History',
  StringStyles.shareArticleTitle: 'Share articles',
  StringStyles.shareArticleEnter: 'Share to this app',
  StringStyles.shareArticleHint: 'Give the article a loud title~',
  StringStyles.shareArticleEdit: 'Please enter the title of the article~',
  StringStyles.shareArticleSuccess: 'Successful sharing',
  StringStyles.shareTitle: 'My share',
  StringStyles.collectSuccess: 'Collection success',
  StringStyles.collectQuit: 'Unfavorite successfully',
  StringStyles.notSupportLikes: "Don't support likes at the moment~"
};
